### ISSUE TITLE
Fix addreses

### ISSUE THREAD

**Issue by amin-saffari** [alexdelarge3/SNPCallingComp#1]
Given the fact we have our software or the address to our reference here or there. I am suggesting to remove every fixed address ( [e.g](https://github.com/alexdelarge3/SNPCallingComp/blob/master/scripts/SnakeBromance.v3SA.JM#L13) ) from the snakemake file. Every parameter should be assigned from a config file!

**Comment by starnoux** [comment]
Totally agreed on that, but I am not sur yet that it does work on the server... To be tested first.

💃

**Comment by starnoux** [comment]
As well, I had an issues understanding why fixing the informations at first doesn't work. (I did it to be capable of extracting all informations in another file once it runs... I remembered the advices ;) 
[e.g.](https://github.com/alexdelarge3/SNPCallingComp/blob/master/scripts/SnakeBromance.v3SA.JM#L46)

💃

**Comment by jpnm** [comment]
It doesn’t work yet! So, first we (me and Steph) need to fix everything and then someone needs to do a code optimization (Amin I think you are the man to that job!).

**Comment by amin-saffari** [comment]
It is done
